[package]
name = "red_black_knights"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18.1", default-features = false, features = [
    "bevy_asset",
    "bevy_log",
    "bevy_window",
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "multi_threaded",
    "sysinfo_plugin",
    "tonemapping_luts",

    "bevy_sprite",
    "bevy_sprite_render",
    "bevy_text",
    "bevy_ui",
    "bevy_ui_render",
    "default_font",

    "png",
    "zstd_rust",
    "webgpu",
    "debug",
] }

log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
rand = "0.9"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
dirs = "6"
bevy_egui = { version = "0.39", default-features = false, features = [
    "default_fonts",
    "manage_clipboard",
    "open_url",
    "render",
] }

[target.'cfg(target_os = "linux")'.dependencies]
bevy = { version = "0.18.1", default-features = false, features = ["x11", "wayland"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
codegen-units = 1
