[alias]
rund = "run --features bevy/dynamic_linking"
buildd = "build --features bevy/dynamic_linking"
testd = "test --features bevy/dynamic_linking"

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
